---
abstract: 'We are CPAN Authors of POE'
author:
  - 'Chris Williams'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.47
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.95'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Acme-CPANAuthors-POE
no_index:
  directory:
    - examples
    - inc
    - t
provides:
  Acme::CPANAuthors::POE:
    file: lib/Acme/CPANAuthors/POE.pm
    version: 0.08
requires:
  Acme::CPANAuthors: 0
  perl: 5.6.0
resources:
  homepage: http://github.com/bingos/acme-cpanauthors-poe/tree
  license: http://dev.perl.org/licenses/
  repository: git://github.com/bingos/acme-cpanauthors-poe.git
version: 0.08
