---
abstract: 'We are CPAN Authors of POE'
author:
  - 'Chris Williams'
build_requires:
  Test::More: 0.47
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300017, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Acme-CPANAuthors-POE
requires:
  Acme::CPANAuthors: 0
  perl: v5.6.0
resources:
  homepage: https://github.com/bingos/acme-cpanauthors-poe
  repository: https://github.com/bingos/acme-cpanauthors-poe.git
version: 0.58
